---
abstract: 'This distribution aids in the creation of SADI perl based web services.'
author:
  - "=begin html\r"
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SADI
no_index:
  directory:
    - bin/scripts
    - inc
    - lib/SADI/Generators/templates
    - share
    - t
requires:
  CGI: 0
  Carp: 0
  Class::Inspector: 1.17
  Config::Simple: 4.58
  File::HomeDir: 0.65
  File::Path: 0
  File::ShareDir: 1
  File::Spec: 0.8
  HTTP::Date: 5.81
  HTTP::Request: 0
  IO::Prompt: 0.99.2
  IO::String: 1.08
  LWP: 0
  Log::Log4perl: 1.12
  OWL2Perl: 0.98.1
  Params::Util: 0.38
  RDF::Core: 0.51
  Template: 2.22
  URI: 1.4
  Unicode::String: 2.09
  Want: 0.18
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.07
